# Generated by Django 5.2.5 on 2026-07-10 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_customerprofile_is_bachelor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='academic_year_or_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='allergy_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='delivery_instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='has_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_food_type',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non Vegetarian'), ('halal', 'Halal'), ('low_spicy', 'Low Spicy'), ('high_protein', 'High Protein'), ('diabetic_friendly', 'Diabetic Friendly'), ('custom', 'Custom')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_completion_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='religious',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('christianity', 'Christianity'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='restricted_foods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='spice_level',
            field=models.CharField(blank=True, choices=[('no_spice', 'No Spice'), ('mild', 'Mild'), ('medium', 'Medium'), ('spicy', 'Spicy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('present', 'Present'), ('permanent', 'Permanent')], max_length=20)),
                ('full_address', models.TextField()),
                ('city', models.CharField(blank=True, default='Dhaka', max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('flat_number', models.CharField(blank=True, max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default_delivery', models.BooleanField(default=False)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user_management.customerprofile')),
            ],
            options={
                'verbose_name_plural': 'Customer addresses',
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
