# Generated by Django 5.2.5 on 2026-07-27 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_customeraddress_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDeliveryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('city', models.CharField(blank=True, default='Dhaka', max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('flat_number', models.CharField(blank=True, max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_places', to='user_management.customerprofile')),
            ],
            options={
                'verbose_name_plural': 'Customer delivery places',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealDeliveryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_delivery_preference', to='user_management.customerprofile')),
                ('dinner_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_preference_set', to='user_management.customerdeliveryplace')),
                ('lunch_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_preference_set', to='user_management.customerdeliveryplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealDeliveryDayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_period', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(help_text='ISO weekday: Monday=0 … Sunday=6.')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_delivery_day_overrides', to='user_management.customerprofile')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_overrides', to='user_management.customerdeliveryplace')),
            ],
            options={
                'ordering': ['weekday', 'meal_period'],
                'constraints': [models.UniqueConstraint(fields=('customer_profile', 'meal_period', 'weekday'), name='unique_meal_delivery_day_override'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='meal_delivery_day_override_weekday_range')],
            },
        ),
    ]
