# Generated by Django 5.2.5 on 2026-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_customerprofile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='is_bachelor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('job_holder', 'Job Holder'), ('freelancer', 'Freelancer'), ('business_owner', 'Business Owner'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
