# Generated by Django 5.2.5 on 2026-08-29 14:32

import user_management.services.profile_picture
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_customer_profile_nullable_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user_management.services.profile_picture.profile_picture_upload_path),
        ),
    ]
