# Generated by Django 5.2.5 on 2026-08-31 23:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_customer_auth_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate_radius_km', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Reject new/updated places within this distance (km) of another active place.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_active_delivery_places', models.PositiveSmallIntegerField(default=3, help_text='Maximum active delivery places per customer.', validators=[django.core.validators.MinValueValidator(1)])),
                ('location_refresh_interval_hours', models.PositiveIntegerField(default=24, help_text='Hours after last detection before clients should prompt GPS again.', validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer location settings',
                'verbose_name_plural': 'Customer location settings',
            },
        ),
        migrations.AddField(
            model_name='customerdeliveryplace',
            name='formatted_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='customerdeliveryplace',
            name='is_verified_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdeliveryplace',
            name='location_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters when provided.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerdeliveryplace',
            name='location_source',
            field=models.CharField(blank=True, choices=[('gps', 'GPS'), ('manual', 'Manual'), ('map_pin', 'Map pin'), ('search', 'Search'), ('guest_migration', 'Guest migration')], default='', help_text='Blank for legacy places created before location enrichment.', max_length=32),
        ),
        migrations.CreateModel(
            name='CustomerLocationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('saved_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('saved_location_name', models.CharField(blank=True, default='', max_length=255)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('last_detected_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_detected_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_detected_location_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_detected_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_delivery_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_location_preferences', to='user_management.customerdeliveryplace')),
                ('customer_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_preference', to='user_management.customerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
