# Generated by Django 5.2.5 on 2026-09-01 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_deduplicate_device_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='app_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='devicetoken_user_active_idx'),
        ),
    ]
