# Generated by Django 5.2.5 on 2026-09-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_customerprofile_meal_service_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('student', 'Student'), ('job_holder', 'Job Holder'), ('freelancer', 'Freelancer'), ('business_owner', 'Business Owner'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=30, null=True)),
                ('is_bachelor', models.BooleanField(blank=True, null=True)),
                ('otp_code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('otp_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('otp_max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('otp_issue_count', models.PositiveSmallIntegerField(default=0)),
                ('otp_window_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='pendingreg_expires_idx'), models.Index(fields=['email', 'expires_at'], name='pendingreg_email_exp_idx')],
            },
        ),
    ]
