# Generated by Django 5.2.5 on 2026-09-03 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_area', '0001_initial'),
        ('user_management', '0018_pending_customer_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLocationOfferResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_session_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('suppressed', 'Suppressed')], max_length=20)),
                ('resolved_at', models.DateTimeField()),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_location_offer_resolutions', to='user_management.customerprofile')),
                ('delivery_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_offer_resolutions', to='user_management.customerdeliveryplace')),
                ('service_area_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_offer_resolutions', to='service_area.servicearearequest')),
            ],
            options={
                'indexes': [models.Index(fields=['customer_profile', 'guest_session_id'], name='um_guest_offer_cust_sess_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer_profile', 'guest_session_id'), name='unique_guest_location_offer_resolution')],
            },
        ),
    ]
