# Generated by Django 5.2.5 on 2026-09-04 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_tokens(apps, schema_editor):
    """Copy existing DRF Token rows into AuthSession for seamless Token-header auth."""
    Token = apps.get_model('authtoken', 'Token')
    AuthSession = apps.get_model('user_management', 'AuthSession')
    existing_keys = set(AuthSession.objects.values_list('key', flat=True))
    sessions = []
    for token in Token.objects.all().iterator():
        if token.key in existing_keys:
            continue
        sessions.append(
            AuthSession(
                key=token.key,
                user_id=token.user_id,
            )
        )
        existing_keys.add(token.key)
    if sessions:
        AuthSession.objects.bulk_create(sessions, batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('user_management', '0019_guest_location_offer_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhoneAuthOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=10)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('issue_window_started_at', models.DateTimeField(blank=True, null=True)),
                ('issues_in_window', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='phoneauthotp_phone_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('device_token', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='authsession_user_revoked_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple')], db_index=True, max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email_at_link', models.EmailField(blank=True, default='', max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='socialidentity_user_prov_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='socialidentity_provider_userid_uniq')],
            },
        ),
        migrations.RunPython(migrate_legacy_tokens, noop_reverse),
    ]
