# Generated by Django 5.2.5 on 2026-09-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_multi_provider_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcustomerregistration',
            name='referral_client_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='pendingcustomerregistration',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='pendingcustomerregistration',
            name='referral_intent_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingcustomerregistration',
            name='referrer_snapshot_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
