# Generated by Django 5.2.17 on 2026-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_referral_affiliate_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdeliveryplace',
            name='city',
            field=models.CharField(blank=True, default='Chittagong', max_length=100),
        ),
    ]
