# Generated by Django 5.2.5 on 2026-09-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_zones', '0001_delivery_zones_initial'),
        ('user_management', '0022_alter_customerdeliveryplace_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='delivery_location',
            field=models.ForeignKey(blank=True, help_text='Manual operational location; derived zone comes from location.zone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='delivery_zones.deliverylocation'),
        ),
    ]
