# Generated by Django 5.2.5 on 2026-09-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(default='1.0.13', help_text='Newest version advertised to clients (semver X.Y.Z).', max_length=32)),
                ('minimum_supported_version', models.CharField(default='1.0.13', help_text='Oldest version allowed without force update (semver X.Y.Z).', max_length=32)),
                ('play_store_url', models.URLField(default='https://play.google.com/store/apps/details?id=bd.com.befood', help_text='Google Play listing URL for Update Now.', max_length=512)),
                ('app_store_url', models.URLField(blank=True, default='', help_text='Apple App Store listing URL (optional until iOS publish).', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App version settings',
                'verbose_name_plural': 'App version settings',
            },
        ),
    ]
