# Generated by Django 5.2.17 on 2026-09-29 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Lower values appear first on the home carousel (1 = first).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
