# Generated by Django 5.1.3

import meals.services.meal_image
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_thumbnail', models.ImageField(upload_to=meals.services.meal_image.meal_thumbnail_upload_path)),
                ('meal_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('half_monthly', 'Half Monthly'), ('six_monthly', '6 Monthly'), ('one_year', '1 Year')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Category',
                'verbose_name_plural': 'Meal Categories',
                'ordering': ['-created_at'],
            },
        ),
    ]
