# Generated by Django 5.1.3 on 2026-07-09 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='meal_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('half_monthly', 'Half Monthly'), ('monthly', 'Monthly'), ('six_months', 'Six Months'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
