# Generated by Django 5.1.3 on 2026-07-09 18:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_mealcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcategory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
