# Generated by Django 5.2.5 on 2026-07-22 08:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_ingredient_mealrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_customer',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Required for flat-cost items. Ignored when kg pricing is complete.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product_role',
            field=models.CharField(choices=[('main', 'Main'), ('side', 'Side'), ('staple', 'Staple'), ('seasoning', 'Seasoning'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='customers_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='MealCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cycle_days', models.PositiveSmallIntegerField()),
                ('total_meals', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_meal_cycle_year_month')],
            },
        ),
        migrations.CreateModel(
            name='MealCyclePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_cost_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('profit_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('snapshot_product_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('snapshot_other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('snapshot_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('snapshot_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('snapshot_per_meal_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='meals.mealcycle')),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_plans', to='meals.mealcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealCyclePlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_plan_lines', to='meals.ingredient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='meals.mealcycleplan')),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.DeleteModel(
            name='MealRecipe',
        ),
        migrations.AddConstraint(
            model_name='mealcycleplan',
            constraint=models.UniqueConstraint(fields=('cycle', 'meal_category'), name='unique_meal_cycle_plan_per_category'),
        ),
        migrations.AddConstraint(
            model_name='mealcycleplanline',
            constraint=models.UniqueConstraint(fields=('plan', 'ingredient'), name='unique_cycle_plan_line_ingredient'),
        ),
    ]
