# Generated by Django 5.2.5 on 2026-07-22 10:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meal_cycle_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcategory',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Published package price from cycle finalize. Null until first finalize.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
