# Generated by Django 5.2.5 on 2026-07-22 12:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_meal_total_price_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRevealSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('lunch_reveal_time', models.TimeField(default=datetime.time(8, 0))),
                ('dinner_reveal_time', models.TimeField(default=datetime.time(16, 0))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu reveal settings',
                'verbose_name_plural': 'Menu reveal settings',
            },
        ),
        migrations.CreateModel(
            name='MonthlyMenuSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_schedule', to='meals.mealcycleplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMenuSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('meal_period', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='meals.monthlymenuschedule')),
            ],
            options={
                'ordering': ['service_date', 'meal_period'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMenuSlotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_slot_items', to='meals.ingredient')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.monthlymenuslot')),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlymenuslot',
            constraint=models.UniqueConstraint(fields=('schedule', 'service_date', 'meal_period'), name='unique_menu_slot_per_schedule_date_period'),
        ),
        migrations.AddConstraint(
            model_name='monthlymenuslotitem',
            constraint=models.UniqueConstraint(fields=('slot', 'ingredient'), name='unique_menu_slot_item_ingredient'),
        ),
    ]
