# Generated by Django 5.2.5 on 2026-08-04 12:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_plan_level_ingredient_role_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcycleplan',
            name='other_cost_percent',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_customer',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional per-serving cooking cost for one customer or one piece. Leave empty when unknown. Ignored when kg pricing is complete. Required before the ingredient is used on a meal-cycle plan.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.CreateModel(
            name='OperationalCostMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_meal_quantity', models.PositiveIntegerField(help_text='Planned meal sales volume used to allocate monthly overhead per meal.', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_operational_cost_month_year_month')],
            },
        ),
        migrations.CreateModel(
            name='OperationalCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.operationalcostmonth')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
