# Generated by Django 5.2.5 on 2026-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_operational_cost_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymenuslot',
            name='final_meal_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Published final selling price for this lunch/dinner slot.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlymenuslot',
            name='ingredient_cost_lines',
            field=models.JSONField(blank=True, help_text='Audit lines of unit costs used when the slot price was published.', null=True),
        ),
        migrations.AddField(
            model_name='monthlymenuslot',
            name='ingredient_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlymenuslot',
            name='operational_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='monthlymenuslot',
            name='profit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
