# Generated by Django 5.2.5 on 2026-08-18 10:22

from django.db import migrations, models
from django.db.models import Q


def mark_ongoing_packages_subscribable(apps, schema_editor):
    MealCategory = apps.get_model('meals', 'MealCategory')
    MealCategory.objects.filter(
        Q(meal_name__icontains='student')
        | Q(meal_name__icontains='regular')
        | Q(meal_name__icontains='premium')
        | Q(meal_type='monthly')
    ).update(is_subscribable=True)


def unmark_ongoing_packages_subscribable(apps, schema_editor):
    MealCategory = apps.get_model('meals', 'MealCategory')
    MealCategory.objects.filter(is_subscribable=True).update(is_subscribable=False)


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_backfill_slot_final_price_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='is_subscribable',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'When true, verified customers may subscribe to this package as an '
                    'open-ended meal plan (Student/Regular/Premium style).'
                ),
            ),
        ),
        migrations.RunPython(
            mark_ongoing_packages_subscribable,
            unmark_ongoing_packages_subscribable,
        ),
    ]
