# Generated by Django 5.2.5 on 2026-08-28 16:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_subscription_based_meal_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantMealSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Profit percent applied to Instant Meal ingredient cost only.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))])),
                ('duration_days', models.PositiveSmallIntegerField(choices=[(1, 'Today'), (3, '3 Days'), (7, '7 Days'), (15, '15 Days'), (25, '25 Days'), (30, '30 Days')], default=7, help_text='Public Instant Meal window length in days from today (1=Today).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instant meal settings',
                'verbose_name_plural': 'Instant meal settings',
            },
        ),
    ]
