# Generated by Django 5.2.5 on 2026-08-08 06:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0011_meal_demand_snapshot'),
        ('user_management', '0010_customerprofile_public_id'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='platform', max_length=32, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], default='active', max_length=20)),
                ('total_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_manual_added', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_customer_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Admin wallet',
                'verbose_name_plural': 'Admin wallets',
            },
        ),
        migrations.CreateModel(
            name='AdminWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('customer_payment', 'Customer payment'), ('manual_deposit', 'Manual deposit'), ('adjustment', 'Adjustment'), ('refund_reversal', 'Refund reversal'), ('other_income', 'Other income'), ('withdrawal', 'Withdrawal'), ('customer_refund', 'Customer refund'), ('restaurant_settlement', 'Restaurant settlement'), ('rider_payment', 'Rider payment'), ('operational_expense', 'Operational expense'), ('onahar_expense', 'Onahar expense'), ('promotional_cost', 'Promotional cost'), ('platform_expense', 'Platform expense'), ('manual_adjustment', 'Manual adjustment')], max_length=40)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('wallet', 'Customer wallet'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('other', 'Other')], default='manual', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_wallet_transactions', to='user_management.adminprofile')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_wallet_transactions', to='user_management.customerprofile')),
                ('customer_wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_wallet_credits', to='wallet.wallettransaction')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_wallet_transactions', to='orders.order')),
                ('order_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_wallet_transactions', to='orders.orderdelivery')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='admin_wallet.adminwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminWalletAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('manual_deposit', 'Manual deposit'), ('withdrawal', 'Withdrawal'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_wallet_audit_logs', to='user_management.adminprofile')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='admin_wallet.adminwallettransaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='adminwallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='admin_walle_wallet__96a57e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallettransaction',
            index=models.Index(fields=['status'], name='admin_walle_status_0b971d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallettransaction',
            index=models.Index(fields=['type'], name='admin_walle_type_71689c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallettransaction',
            index=models.Index(fields=['direction'], name='admin_walle_directi_86fe7c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallettransaction',
            index=models.Index(fields=['method'], name='admin_walle_method_1c338e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwallettransaction',
            index=models.Index(fields=['-created_at'], name='admin_walle_created_b63ba0_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminwallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('wallet', 'idempotency_key'), name='admin_wallet_txn_unique_idempotency'),
        ),
        migrations.AddIndex(
            model_name='adminwalletauditlog',
            index=models.Index(fields=['action', '-created_at'], name='admin_walle_action_4da3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='adminwalletauditlog',
            index=models.Index(fields=['-created_at'], name='admin_walle_created_67eea5_idx'),
        ),
    ]
