# Generated by Django 5.2.5 on 2026-08-08 06:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_wallet', '0002_seed_platform_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='total_customer_funding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='adminwallet',
            name='total_customer_withdrawals',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='adminwallettransaction',
            name='type',
            field=models.CharField(choices=[('customer_payment', 'Customer payment'), ('customer_funding', 'Customer funding'), ('manual_deposit', 'Manual deposit'), ('adjustment', 'Adjustment'), ('refund_reversal', 'Refund reversal'), ('other_income', 'Other income'), ('withdrawal', 'Withdrawal'), ('customer_withdraw', 'Customer withdraw'), ('customer_refund', 'Customer refund'), ('restaurant_settlement', 'Restaurant settlement'), ('rider_payment', 'Rider payment'), ('operational_expense', 'Operational expense'), ('onahar_expense', 'Onahar expense'), ('promotional_cost', 'Promotional cost'), ('platform_expense', 'Platform expense'), ('manual_adjustment', 'Manual adjustment')], max_length=40),
        ),
    ]
