# Generated by Django 5.2.5 on 2026-09-13 08:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_wallet', '0005_referral_commission_types'),
        ('meals', '0017_instant_meal_settings'),
        ('orders', '0016_align_meal_off_cutoff_same_day'),
        ('user_management', '0022_alter_customerdeliveryplace_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealProfitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_period', models.CharField(max_length=20)),
                ('service_date', models.DateField()),
                ('meal_price', models.DecimalField(decimal_places=2, help_text='Customer charged amount (revenue) frozen at recognition.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('food_cost', models.DecimalField(decimal_places=2, help_text='Published slot ingredient_cost_snapshot frozen at recognition.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('operational_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Published slot operational_cost_snapshot frozen at recognition.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit_amount', models.DecimalField(decimal_places=2, help_text='Published slot profit_snapshot frozen at recognition.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='profit_amount / meal_price * 100 when meal_price > 0, else 0.', max_digits=8)),
                ('source', models.CharField(choices=[('auto_delivery', 'Auto delivery'), ('manual_delivery', 'Manual delivery'), ('backfill', 'Historical backfill')], max_length=32)),
                ('package_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_profit_transactions', to='user_management.customerprofile')),
                ('order_delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='meal_profit_transaction', to='orders.orderdelivery')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_profit_transactions', to='meals.mealcategory')),
            ],
            options={
                'verbose_name': 'Meal profit transaction',
                'verbose_name_plural': 'Meal profit transactions',
                'ordering': ['-service_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['service_date'], name='admin_walle_service_0e2fc9_idx'), models.Index(fields=['package', 'service_date'], name='admin_walle_package_a33b63_idx'), models.Index(fields=['customer', 'service_date'], name='admin_walle_custome_36fd27_idx'), models.Index(fields=['meal_period', 'service_date'], name='admin_walle_meal_pe_8e829a_idx'), models.Index(fields=['-service_date', '-id'], name='admin_walle_service_040b2d_idx')],
            },
        ),
    ]
