# Generated by Django 5.2.5 on 2026-09-06 00:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_wallet', '0005_referral_commission_types'),
        ('orders', '0016_align_meal_off_cutoff_same_day'),
        ('user_management', '0021_referral_affiliate_system'),
        ('wallet', '0005_dual_bucket_balances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Referral code must be BEF followed by 8 alphanumeric characters.', regex='^BEF[A-Z0-9]{8}$')])),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('last_shared_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to='user_management.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_service_date', models.DateField(blank=True, null=True)),
                ('meal_period', models.CharField(blank=True, default='', max_length=16)),
                ('meal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('status_reason', models.CharField(blank=True, default='', max_length=64)),
                ('status_detail', models.CharField(blank=True, default='', max_length=255)),
                ('is_manual', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commission_actions', to=settings.AUTH_USER_MODEL)),
                ('admin_wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commissions', to='admin_wallet.adminwallettransaction')),
                ('customer_wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commissions', to='wallet.wallettransaction')),
                ('order_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_commissions', to='orders.orderdelivery')),
                ('referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions_generated', to='user_management.customerprofile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions_earned', to='user_management.customerprofile')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='referrals.referralcommission')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', 'created_at'], name='referrals_r_referre_e401f8_idx'), models.Index(fields=['referred'], name='referrals_r_referre_95fc7a_idx'), models.Index(fields=['order_delivery'], name='referrals_r_order_d_a063b1_idx'), models.Index(fields=['status'], name='referrals_r_status_bc4f00_idx'), models.Index(fields=['status', 'created_at'], name='referrals_r_status_8ba1cc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order_delivery__isnull', False), ('is_manual', False), ('reversal_of__isnull', True)), fields=('order_delivery',), name='referral_commission_unique_delivery')],
            },
        ),
        migrations.CreateModel(
            name='ReferralRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code_used', models.CharField(max_length=16)),
                ('source_client', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web')], default='mobile', max_length=16)),
                ('attributed_at', models.DateTimeField()),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_relationship', to='user_management.customerprofile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='user_management.customerprofile')),
            ],
            options={
                'ordering': ['-attributed_at'],
                'indexes': [models.Index(fields=['referrer'], name='referrals_r_referre_65e7d3_idx'), models.Index(fields=['attributed_at'], name='referrals_r_attribu_ace963_idx'), models.Index(fields=['referrer', 'attributed_at'], name='referrals_r_referre_348583_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralValidationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('is_valid', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_validation_events', to='user_management.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='referrals_r_created_e9e3bb_idx'), models.Index(fields=['is_valid', 'created_at'], name='referrals_r_is_vali_b4d749_idx')],
            },
        ),
    ]
