# Generated by Django 5.2.5 on 2026-09-10 22:55

import django.core.validators
from decimal import Decimal, InvalidOperation

from django.conf import settings
from django.db import migrations, models


def _seed_percent() -> Decimal:
    raw = getattr(settings, 'REFERRAL_COMMISSION_PERCENT', '5')
    try:
        value = Decimal(str(raw)).quantize(Decimal('0.01'))
    except (InvalidOperation, TypeError, ValueError):
        return Decimal('5.00')
    if value < 0 or value > 100:
        return Decimal('5.00')
    return value


def seed_referral_program_settings(apps, schema_editor):
    ReferralProgramSettings = apps.get_model('referrals', 'ReferralProgramSettings')
    if not ReferralProgramSettings.objects.filter(pk=1).exists():
        ReferralProgramSettings.objects.create(
            pk=1,
            commission_percent=_seed_percent(),
        )


def unseed_referral_program_settings(apps, schema_editor):
    ReferralProgramSettings = apps.get_model('referrals', 'ReferralProgramSettings')
    ReferralProgramSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_referral_affiliate_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgramSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'commission_percent',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('5.00'),
                        help_text=(
                            'Percent of charged meal amount credited as referral '
                            'commission (0–100).'
                        ),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.00')),
                            django.core.validators.MaxValueValidator(Decimal('100.00')),
                        ],
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral program settings',
                'verbose_name_plural': 'Referral program settings',
            },
        ),
        migrations.RunPython(
            seed_referral_program_settings,
            unseed_referral_program_settings,
        ),
    ]
