# Generated by Django 5.1.3 on 2026-07-27 07:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'asset category',
                'verbose_name_plural': 'asset categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='assets_asse_is_acti_38a54e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermanentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(help_text='Unique label/code for physical identification.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('in_service', 'In service'), ('under_maintenance', 'Under maintenance'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='in_service', max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Use 1 for a single tagged unit; >1 for homogeneous batches.', validators=[django.core.validators.MinValueValidator(1)])),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_assets', to='business.outlet')),
            ],
            options={
                'verbose_name': 'permanent asset',
                'verbose_name_plural': 'permanent assets',
                'ordering': ['name', 'asset_tag'],
                'indexes': [models.Index(fields=['asset_tag'], name='assets_perm_asset_t_1dd56a_idx'), models.Index(fields=['status'], name='assets_perm_status_4cc882_idx'), models.Index(fields=['is_active'], name='assets_perm_is_acti_b63b82_idx'), models.Index(fields=['status', 'is_active'], name='assets_perm_status_f37cca_idx')],
            },
        ),
    ]
