# Generated by Django 5.2.5 on 2026-07-27 17:27

import blogs.utils.cover_image
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower values appear first in admin filters.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blog categories',
                'ordering': ['sort_order', 'created_at', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='blogs_blogc_is_acti_667bce_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=blogs.utils.cover_image.blog_cover_upload_path)),
                ('cover_image_title', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blogs.blogcategory')),
            ],
            options={
                'verbose_name': 'blog article',
                'verbose_name_plural': 'blog articles',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='blogs_bloga_is_publ_587001_idx'), models.Index(fields=['is_published', 'view_count'], name='blogs_bloga_is_publ_05c320_idx'), models.Index(fields=['category', 'is_published'], name='blogs_bloga_categor_d21d77_idx')],
            },
        ),
    ]
