# Generated by Django 5.2.5 on 2026-07-26 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255)),
                ('body_en', models.TextField(blank=True)),
                ('body_bn', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Optional start time (UTC). Null = eligible immediately when published.', null=True)),
                ('publish_until', models.DateTimeField(blank=True, help_text='Optional end time (UTC). Null = no automatic expiry.', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower values appear first on the public feed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'ordering': ['sort_order', '-publish_at', '-created_at'],
            },
        ),
    ]
