# Generated by Django 5.2.5 on 2026-08-07 18:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0011_meal_demand_snapshot'),
        ('user_management', '0010_customerprofile_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnaharSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_target', models.PositiveIntegerField(default=50, help_text='Eligible meals required for one Onahar meal contribution.', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_contributed_meals', models.PositiveIntegerField(default=0)),
                ('total_distributed_meals', models.PositiveIntegerField(default=0)),
                ('available_meals', models.IntegerField(default=0, help_text='Denormalized: contributed − distributed (may go negative only via adjustments).')),
            ],
            options={
                'verbose_name': 'Onahar settings',
                'verbose_name_plural': 'Onahar settings',
            },
        ),
        migrations.CreateModel(
            name='OnaharContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.CharField(max_length=7)),
                ('meals', models.IntegerField(help_text='+1 earned contribution or -1 compensating adjustment')),
                ('kind', models.CharField(choices=[('earned', 'Earned'), ('adjustment', 'Adjustment')], default='earned', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onahar_contributions', to='user_management.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnaharDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('full_address', models.TextField(blank=True, default='')),
                ('distribution_date', models.DateField()),
                ('meals_distributed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, default='')),
                ('beneficiary_info', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onahar_distributions_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onahar_distributions_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onahar_distributions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-distribution_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnaharDistributionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='onahar/distributions/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='onahar.onahardistribution')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onahar_distribution_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnaharFundLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('meals', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('entry_type', models.CharField(choices=[('contribution', 'Contribution'), ('contribution_adjustment', 'Contribution adjustment'), ('distribution', 'Distribution'), ('distribution_restore', 'Distribution restore')], max_length=40)),
                ('balance_after', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_ledger_entries', to='onahar.onaharcontribution')),
                ('distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_ledger_entries', to='onahar.onahardistribution')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OnaharMonthlyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.CharField(help_text='YYYY-MM in project timezone', max_length=7)),
                ('target_snapshot', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('net_points', models.IntegerField(default=0)),
                ('contributions_earned', models.PositiveIntegerField(default=0)),
                ('expired_points', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onahar_monthly_progress', to='user_management.customerprofile')),
            ],
            options={
                'ordering': ['-year_month', '-id'],
            },
        ),
        migrations.AddField(
            model_name='onaharcontribution',
            name='monthly_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='onahar.onaharmonthlyprogress'),
        ),
        migrations.CreateModel(
            name='OnaharPointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('credit', 'Credit'), ('reverse', 'Reverse')], max_length=20)),
                ('year_month', models.CharField(max_length=7)),
                ('points_delta', models.SmallIntegerField(help_text='+1 for credit, -1 for reverse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onahar_point_events', to='user_management.customerprofile')),
                ('order_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onahar_point_events', to='orders.orderdelivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnaharPrivacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_mode', models.CharField(choices=[('public', 'Public'), ('partial', 'Partial'), ('anonymous', 'Anonymous')], default='partial', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onahar_privacy', to='user_management.customerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnaharTargetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_target', models.PositiveIntegerField()),
                ('new_target', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onahar_target_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnaharAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onahar_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='onahar_onah_action_d2f056_idx'), models.Index(fields=['-created_at'], name='onahar_onah_created_fba302_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='onahardistribution',
            index=models.Index(fields=['status', '-distribution_date'], name='onahar_onah_status_65f249_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharfundledgerentry',
            index=models.Index(fields=['-created_at'], name='onahar_onah_created_be1af4_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharfundledgerentry',
            index=models.Index(fields=['entry_type', '-created_at'], name='onahar_onah_entry_t_aebd06_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharfundledgerentry',
            index=models.Index(fields=['direction', '-created_at'], name='onahar_onah_directi_3f9c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharmonthlyprogress',
            index=models.Index(fields=['year_month', 'status'], name='onahar_onah_year_mo_4fd247_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharmonthlyprogress',
            index=models.Index(fields=['customer', '-year_month'], name='onahar_onah_custome_c7a06e_idx'),
        ),
        migrations.AddConstraint(
            model_name='onaharmonthlyprogress',
            constraint=models.UniqueConstraint(fields=('customer', 'year_month'), name='onahar_unique_customer_month_progress'),
        ),
        migrations.AddIndex(
            model_name='onaharcontribution',
            index=models.Index(fields=['customer', '-created_at'], name='onahar_onah_custome_639763_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharcontribution',
            index=models.Index(fields=['year_month'], name='onahar_onah_year_mo_eb0dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharcontribution',
            index=models.Index(fields=['-created_at'], name='onahar_onah_created_a557b9_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharpointevent',
            index=models.Index(fields=['customer', 'year_month'], name='onahar_onah_custome_0044ff_idx'),
        ),
        migrations.AddIndex(
            model_name='onaharpointevent',
            index=models.Index(fields=['order_delivery'], name='onahar_onah_order_d_fbf60d_idx'),
        ),
        migrations.AddConstraint(
            model_name='onaharpointevent',
            constraint=models.UniqueConstraint(fields=('order_delivery', 'event_type'), name='onahar_unique_delivery_point_event_type'),
        ),
    ]
