# Generated by Django 5.2.5 on 2026-08-08 07:17

import django.core.validators
import django.db.models.deletion
import inventory.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_wallet', '0004_inventory_and_wallet_types'),
        ('meals', '0015_backfill_slot_final_price_snapshots'),
        ('user_management', '0010_customerprofile_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(db_index=True, max_length=255, unique=True)),
                ('default_unit', models.CharField(choices=[('kg', 'KG'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('bottle', 'Bottle'), ('bag', 'Bag')], max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('minimum_stock_level', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('average_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_created', to='user_management.adminprofile')),
                ('linked_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='meals.ingredient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('bottle', 'Bottle'), ('bag', 'Bag')], max_length=20)),
                ('quantity_delta_base', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to='user_management.adminprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryKitchenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('bottle', 'Bottle'), ('bag', 'Bag')], max_length=20)),
                ('quantity_base', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('purpose', models.CharField(blank=True, default='', max_length=255)),
                ('menu_reference', models.CharField(blank=True, default='', max_length=255)),
                ('kitchen_batch', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_kitchen_usages', to='user_management.adminprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_usages', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('invoice', models.FileField(blank=True, null=True, upload_to=inventory.models.inventory_invoice_upload_path)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchases_cancelled', to='user_management.adminprofile')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchases_confirmed', to='user_management.adminprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchases_created', to='user_management.adminprofile')),
                ('reversal_wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchase_reversals', to='admin_wallet.adminwallettransaction')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchases', to='admin_wallet.adminwallettransaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('item_created', 'Item created'), ('item_updated', 'Item updated'), ('purchase_added', 'Purchase added'), ('purchase_confirmed', 'Purchase confirmed'), ('purchase_cancelled', 'Purchase cancelled'), ('stock_used', 'Stock used'), ('stock_adjusted', 'Stock adjusted'), ('wastage_added', 'Wastage added'), ('invoice_uploaded', 'Invoice uploaded'), ('wallet_deducted', 'Wallet deducted'), ('wallet_reversed', 'Wallet reversed')], max_length=40)),
                ('previous_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_logs', to='user_management.adminprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory.inventoryitem')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory.inventorypurchase')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('bottle', 'Bottle'), ('bag', 'Bag')], max_length=20)),
                ('quantity_base', models.DecimalField(decimal_places=3, help_text='Quantity converted to the item default unit.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per item default unit.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.inventoryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorypurchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryWastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('bottle', 'Bottle'), ('bag', 'Bag')], max_length=20)),
                ('quantity_base', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('reason', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastages', to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_wastages', to='user_management.adminprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('kitchen_usage', 'Kitchen usage'), ('wastage', 'Wastage'), ('adjustment', 'Adjustment'), ('purchase_reversal', 'Purchase reversal')], max_length=40)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(choices=[('kg', 'KG'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('packet', 'Packet'), ('box', 'Box'), ('bottle', 'Bottle'), ('bag', 'Bag')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('unit_cost_at_movement', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stock_movements', to='user_management.adminprofile')),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventoryadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
                ('kitchen_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorykitchenusage')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorypurchase')),
                ('purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorypurchaseline')),
                ('wastage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorywastage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['status'], name='inventory_i_status_77888d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_fe6a79_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['-updated_at'], name='inventory_i_updated_ef0de3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorykitchenusage',
            index=models.Index(fields=['item', '-created_at'], name='inventory_i_item_id_c7366f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorykitchenusage',
            index=models.Index(fields=['-created_at'], name='inventory_i_created_965e38_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchase',
            index=models.Index(fields=['status', '-created_at'], name='inventory_i_status_e3d74c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchase',
            index=models.Index(fields=['supplier'], name='inventory_i_supplie_18b393_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorypurchase',
            index=models.Index(fields=['-purchase_date'], name='inventory_i_purchas_149c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditlog',
            index=models.Index(fields=['action', '-created_at'], name='inventory_i_action_ba1788_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditlog',
            index=models.Index(fields=['-created_at'], name='inventory_i_created_e0942b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockmovement',
            index=models.Index(fields=['item', '-created_at'], name='inventory_i_item_id_7ee7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockmovement',
            index=models.Index(fields=['type', '-created_at'], name='inventory_i_type_50d1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockmovement',
            index=models.Index(fields=['-created_at'], name='inventory_i_created_b1769d_idx'),
        ),
    ]
