# Generated by Django 5.2.5 on 2026-09-17 18:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0022_alter_customerdeliveryplace_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('priority', models.PositiveIntegerField(help_text='Lower number = higher planning priority.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('external_map_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('geo_metadata', models.JSONField(blank=True, null=True)),
                ('assigned_delivery_man', models.ForeignKey(blank=True, help_text='Primary Delivery Man for this zone (phase 1: one zone per rider).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_delivery_zones', to='user_management.riderprofile')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveIntegerField(help_text='Lower number = closer / deliver first within the zone.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('external_map_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('geo_metadata', models.JSONField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='delivery_zones.deliveryzone')),
            ],
            options={
                'ordering': ['zone__priority', 'priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['status', 'priority'], name='delivery_zo_status_d12559_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('priority',), name='uniq_active_delivery_zone_priority'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_delivery_man__isnull', False)), fields=('assigned_delivery_man',), name='uniq_delivery_zone_assigned_rider'),
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['zone', 'status', 'priority'], name='delivery_zo_zone_id_ec42f5_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['status', 'name'], name='delivery_zo_status_6c923c_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverylocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('zone', 'priority'), name='uniq_active_delivery_location_priority_per_zone'),
        ),
    ]
