# Generated by Django 5.2.5 on 2026-09-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def _assert_no_duplicate_provider_recharge_refs(apps, schema_editor):
    """
    Fail loudly if historical provider recharge refs would violate the new
    partial unique constraint. Ops must resolve duplicates before migrating.
    """
    WalletTransaction = apps.get_model('wallet', 'WalletTransaction')
    duplicates = (
        WalletTransaction.objects.filter(
            type='recharge',
            method__in=['bkash', 'nagad', 'bank'],
        )
        .exclude(external_ref='')
        .values('method', 'external_ref')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    rows = list(duplicates)
    if not rows:
        return
    sample = ', '.join(
        f"{row['method']}:{row['external_ref']}×{row['cnt']}" for row in rows[:10]
    )
    raise RuntimeError(
        'Cannot add wallet_txn_unique_provider_recharge_ref: duplicate provider '
        f'recharge refs exist ({len(rows)} groups). Resolve before migrating. '
        f'Sample: {sample}'
    )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_wallet_transactions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='method',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual'),
                    ('bkash', 'bKash'),
                    ('nagad', 'Nagad'),
                    ('bank', 'Bank'),
                ],
                default='manual',
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(
                fields=['type', 'status', '-created_at'],
                name='wallet_wall_type_aedd05_idx',
            ),
        ),
        migrations.RunPython(
            _assert_no_duplicate_provider_recharge_refs,
            _noop_reverse,
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('type', 'recharge'),
                    ('method__in', ['bkash', 'nagad', 'bank']),
                    models.Q(('external_ref', ''), _negated=True),
                ),
                fields=('method', 'external_ref'),
                name='wallet_txn_unique_provider_recharge_ref',
            ),
        ),
    ]
