# Generated by Django 5.2.5 on 2026-09-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_manual_funding_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique receipt identity for completed funding invoices (e.g. recharge).', max_length=64, null=True, unique=True),
        ),
    ]
