# Generated by Django 5.2.5 on 2026-09-07 18:16

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def _assert_no_live_duplicate_provider_refs(apps, schema_editor):
    """
    Fail if pending/completed provider recharge refs would violate the narrowed
    unique constraint. Failed/cancelled rows are intentionally excluded.
    """
    WalletTransaction = apps.get_model('wallet', 'WalletTransaction')
    duplicates = (
        WalletTransaction.objects.filter(
            type='recharge',
            method__in=['bkash', 'nagad', 'bank'],
            status__in=['pending', 'completed'],
        )
        .exclude(external_ref='')
        .values('method', 'external_ref')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    rows = list(duplicates)
    if not rows:
        return
    sample = ', '.join(
        f"{row['method']}:{row['external_ref']}×{row['cnt']}" for row in rows[:10]
    )
    raise RuntimeError(
        'Cannot narrow wallet_txn_unique_provider_recharge_ref: duplicate live '
        f'(pending/completed) provider recharge refs exist ({len(rows)} groups). '
        f'Run `python manage.py audit_wallet_accounting` and resolve before migrating. '
        f'Sample: {sample}'
    )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_txn_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            _assert_no_live_duplicate_provider_refs,
            _noop_reverse,
        ),
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='wallet_txn_unique_provider_recharge_ref',
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('type', 'recharge'),
                    ('method__in', ['bkash', 'nagad', 'bank']),
                    models.Q(('external_ref', ''), _negated=True),
                    ('status__in', ['pending', 'completed']),
                ),
                fields=('method', 'external_ref'),
                name='wallet_txn_unique_provider_recharge_ref',
            ),
        ),
    ]
