# Generated by Django 5.2.5 on 2026-09-16 15:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_alter_customerdeliveryplace_city'),
        ('wallet', '0005_dual_bucket_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('withdraw', 'Withdraw'), ('payment', 'Payment'), ('delivery_fee_payment', 'Delivery fee payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('referral_commission', 'Referral commission'), ('referral_commission_reversal', 'Referral commission reversal')], max_length=40),
        ),
        migrations.CreateModel(
            name='DeliveryFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_month', models.PositiveSmallIntegerField(help_text='Calendar month 1–12 for the billed period.')),
                ('payment_year', models.PositiveSmallIntegerField(help_text='Calendar year for the billed period.')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('reversed', 'Reversed')], default='paid', max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('fee_rule_code', models.CharField(blank=True, default='', max_length=64)),
                ('service_area_public_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fee_payments', to='user_management.customerprofile')),
                ('deducted_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_fee_payments', to='user_management.adminprofile')),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_fee_payment', to='wallet.wallettransaction')),
            ],
            options={
                'ordering': ['-payment_year', '-payment_month', '-created_at'],
                'indexes': [models.Index(fields=['payment_year', 'payment_month', 'status'], name='wallet_deli_payment_6aea3d_idx'), models.Index(fields=['customer', '-payment_year', '-payment_month'], name='wallet_deli_custome_fb1288_idx'), models.Index(fields=['status', '-created_at'], name='wallet_deli_status_ede496_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('customer', 'payment_year', 'payment_month'), name='delivery_fee_unique_paid_per_customer_month'), models.CheckConstraint(condition=models.Q(('payment_month__gte', 1), ('payment_month__lte', 12)), name='delivery_fee_payment_month_range')],
            },
        ),
    ]
