# Generated by Django 5.2.5 on 2026-09-21 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_time', models.TimeField(help_text='Delivery window start (Asia/Dhaka wall-clock).')),
                ('end_time', models.TimeField(help_text='Delivery window end (Asia/Dhaka wall-clock). Must be after start_time.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower values appear first on public and admin lists.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery schedule',
                'verbose_name_plural': 'Delivery schedules',
                'ordering': ['sort_order', 'name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='delivery_sc_is_acti_3e79f6_idx')],
            },
        ),
    ]
