# Generated by Django 5.2.5 on 2026-07-26 17:56

import announcements.utils.banner_image
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('notice', 'Notice'), ('offer', 'Offer'), ('new_package', 'New Package'), ('maintenance', 'Maintenance'), ('announcement', 'Announcement')], default='announcement', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to=announcements.utils.banner_image.announcement_banner_upload_path)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Optional start time (UTC). Null = eligible immediately when published.', null=True)),
                ('publish_until', models.DateTimeField(blank=True, help_text='Optional end time (UTC), inclusive. Null = no automatic expiry. Active while publish_until >= now.', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher values appear first on the public feed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
