# Generated by Django 5.2.5 on 2026-08-09 17:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0010_customerprofile_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_areas_created', to='user_management.adminprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAreaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters when provided by the client.', max_digits=12, null=True)),
                ('detected_location_name', models.CharField(blank=True, default='', max_length=255)),
                ('formatted_address', models.CharField(blank=True, default='', max_length=512)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_serviceable', models.BooleanField(db_index=True, default=False)),
                ('request_kind', models.CharField(choices=[('check', 'Check'), ('demand', 'Demand')], db_index=True, default='check', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_area_requests', to='user_management.customerprofile')),
                ('matched_service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='service_area.servicearea')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['is_active', 'name'], name='service_are_is_acti_8da9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearearequest',
            index=models.Index(fields=['is_serviceable', '-requested_at'], name='service_are_is_serv_fbbea0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearearequest',
            index=models.Index(fields=['request_kind', '-requested_at'], name='service_are_request_46be66_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearearequest',
            index=models.Index(fields=['detected_location_name', '-requested_at'], name='service_are_detecte_493c8a_idx'),
        ),
    ]
