# Generated by Django 5.2.5 on 2026-07-27 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower values appear first on the FAQ page.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ type',
                'verbose_name_plural': 'FAQ types',
                'ordering': ['sort_order', 'created_at', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='faqs_faqtyp_is_acti_8a6b29_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower values appear first within the type.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='faqs.faqtype')),
            ],
            options={
                'verbose_name': 'FAQ question',
                'verbose_name_plural': 'FAQ questions',
                'ordering': ['sort_order', 'created_at', 'id'],
                'indexes': [models.Index(fields=['is_published', 'sort_order'], name='faqs_faqque_is_publ_0ad6aa_idx'), models.Index(fields=['type', 'is_published', 'sort_order'], name='faqs_faqque_type_id_a913c6_idx')],
            },
        ),
    ]
