# Generated by Django 5.2.5 on 2026-08-09 19:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0015_backfill_slot_final_price_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearchPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=255)),
                ('term_normalized', models.CharField(max_length=255, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['sort_order', 'term'],
            },
        ),
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('package', 'Package'), ('instant_meal', 'Instant Meal'), ('food', 'Food'), ('category', 'Category')], db_index=True, max_length=32)),
                ('title_en', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, default='', max_length=255)),
                ('short_description', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, default='', max_length=512)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('popularity_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('category_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_documents', to='meals.ingredient')),
                ('meal_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_documents', to='meals.mealcategory')),
            ],
            options={
                'ordering': ['-popularity_score', 'title_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('keyword_raw', models.CharField(max_length=255)),
                ('locale_hint', models.CharField(choices=[('bn', 'Bangla'), ('en', 'English'), ('banglish', 'Banglish'), ('other', 'Other')], default='other', max_length=16)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='search.searchdocument')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('query_original', models.CharField(max_length=255)),
                ('query_normalized', models.CharField(db_index=True, max_length=255)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('is_zero_result', models.BooleanField(db_index=True, default=False)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_query_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('query_original', models.CharField(blank=True, default='', max_length=255)),
                ('query_normalized', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('clicked_type', models.CharField(blank=True, default='', max_length=32)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_click_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='search.searchdocument')),
                ('query_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='search.searchqueryevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['is_active', 'document_type'], name='search_sear_is_acti_56a02f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['is_active', '-popularity_score'], name='search_sear_is_acti_82deb2_idx'),
        ),
        migrations.AddIndex(
            model_name='searchkeyword',
            index=models.Index(fields=['keyword'], name='search_sear_keyword_ba5792_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchkeyword',
            constraint=models.UniqueConstraint(fields=('document', 'keyword'), name='unique_search_keyword_per_document'),
        ),
        migrations.AddIndex(
            model_name='searchqueryevent',
            index=models.Index(fields=['query_normalized', '-created_at'], name='search_sear_query_n_96eaec_idx'),
        ),
        migrations.AddIndex(
            model_name='searchqueryevent',
            index=models.Index(fields=['is_zero_result', '-created_at'], name='search_sear_is_zero_f7cab1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchclickevent',
            index=models.Index(fields=['clicked_type', '-created_at'], name='search_sear_clicked_ec083f_idx'),
        ),
    ]
