# Generated by Django 5.2.5 on 2026-07-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_meal_package_order_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('meal_period', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delivered', 'Delivered'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_order_deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
            ],
            options={
                'ordering': ['service_date', 'meal_period', 'id'],
                'indexes': [models.Index(fields=['service_date', 'status'], name='orders_orde_service_22212a_idx'), models.Index(fields=['order', 'status'], name='orders_orde_order_i_651640_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'service_date', 'meal_period'), name='unique_order_delivery_slot')],
            },
        ),
    ]
