# Generated by Django 5.2.5 on 2026-07-23 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_package_meal_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('lunch_off_time', models.TimeField(default=datetime.time(23, 59), help_text='Deadline time on the calendar day before the lunch service date.')),
                ('dinner_off_time', models.TimeField(default=datetime.time(14, 0), help_text='Deadline time on the dinner service date.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal off settings',
                'verbose_name_plural': 'Meal off settings',
            },
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='skip_source',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin')], help_text='Who initiated a skip: customer meal-off or admin mark.', max_length=20, null=True),
        ),
    ]
