# Generated by Django 5.2.5 on 2026-07-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_public_id'),
        ('user_management', '0007_meal_delivery_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_area_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_city_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_full_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_label_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_latitude_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_longitude_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_deliveries', to='user_management.customerdeliveryplace'),
        ),
    ]
