# Generated by Django 5.2.5 on 2026-07-29 09:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_meal_delivery_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_wallet_balance_to_order', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Minimum wallet balance (BDT) required to place a meal package order.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order wallet settings',
                'verbose_name_plural': 'Order wallet settings',
            },
        ),
    ]
