# Generated by Django 5.2.5 on 2026-08-04 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_wallet_settings'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='payment_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('charged', 'Charged'), ('failed', 'Failed')], default='not_applicable', help_text='Wallet charge outcome for this slot (charged only after successful delivered debit).', max_length=20),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, help_text='Ledger row for the meal-delivery payment debit, when charged.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_deliveries', to='wallet.wallettransaction'),
        ),
    ]
