# Generated by Django 5.2.5 on 2026-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderdelivery_meal_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='charged_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wallet debit amount when charged (published slot final price).', max_digits=10, null=True),
        ),
    ]
