# Generated by Django 5.2.5 on 2026-08-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_backfill_slot_final_price_snapshots'),
        ('orders', '0010_meal_slot_final_price_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDemandSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('meal_period', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('expected_meal_count', models.PositiveIntegerField()),
                ('meal_off_count', models.PositiveIntegerField()),
                ('final_cooking_count', models.PositiveIntegerField()),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('confirmation_status', models.CharField(choices=[('estimated', 'Estimated'), ('confirmed', 'Confirmed')], default='confirmed', max_length=20)),
                ('ingredient_requirements', models.JSONField(blank=True, default=list, help_text='Frozen ingredient quantity lines at capture time.')),
                ('captured_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_demand_snapshots', to='meals.mealcategory')),
            ],
            options={
                'ordering': ['-service_date', 'meal_period', 'package_id'],
                'indexes': [models.Index(fields=['service_date', 'meal_period'], name='orders_meal_service_55e7f5_idx'), models.Index(fields=['confirmation_status'], name='orders_meal_confirm_fdb881_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_date', 'meal_period', 'package'), name='unique_meal_demand_snapshot_slot_package')],
            },
        ),
    ]
