# Generated by Django 5.2.5 on 2026-08-18 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_subscription_based_meal_service'),
        ('orders', '0011_meal_demand_snapshot'),
        ('user_management', '0011_customer_profile_nullable_onboarding_fields'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('meal_name_snapshot', models.CharField(max_length=255)),
                ('meal_period_snapshot', models.CharField(help_text='lunch | dinner | both at subscribe time.', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('started_on', models.DateField(help_text='Local business date when service starts (meal-off timezone).')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_effective_on', models.DateField(blank=True, help_text='Last local date slots may still be served after cancel.', null=True)),
                ('customer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='orderdelivery',
            name='unique_order_delivery_slot',
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Historical monthly order parent; null for subscription-owned slots.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='skip_source',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin'), ('system', 'System')], help_text='Who initiated a skip: customer, admin, or system (e.g. cancel).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_subscriptions', to='user_management.customerprofile'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='meals.mealcategory'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Active (or cancelled) subscription owning this slot.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.customersubscription'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['subscription', 'status'], name='orders_orde_subscri_e6055e_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'service_date', 'meal_period'), name='unique_order_delivery_slot'),
        ),
        migrations.AddConstraint(
            model_name='orderdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription__isnull', False)), fields=('subscription', 'service_date', 'meal_period'), name='unique_subscription_delivery_slot'),
        ),
        migrations.AddConstraint(
            model_name='orderdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('subscription__isnull', True)), models.Q(('order__isnull', True), ('subscription__isnull', False)), models.Q(('order__isnull', False), ('subscription__isnull', False)), _connector='OR'), name='order_delivery_requires_order_or_subscription'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['status', 'started_on'], name='orders_cust_status_25aace_idx'),
        ),
        migrations.AddConstraint(
            model_name='customersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('customer',), name='unique_active_subscription_per_customer'),
        ),
    ]
