# Generated by Django 5.1.3 on 2026-08-18 12:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_migrate_in_flight_orders_to_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwalletsettings',
            name='min_wallet_balance_to_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Minimum wallet balance (BDT) required to subscribe to a meal plan.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
