# Generated by Django 5.2.5 on 2026-09-20 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_zones', '0001_delivery_zones_initial'),
        ('orders', '0016_align_meal_off_cutoff_same_day'),
        ('user_management', '0023_delivery_zones_initial'),
        ('wallet', '0006_delivery_fee_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.CharField(default='system', help_text='Actor channel: deliveryman, admin, system.', max_length=32)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryManDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lunch_count', models.PositiveIntegerField(default=0)),
                ('dinner_count', models.PositiveIntegerField(default=0)),
                ('total_delivery', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('average_time_seconds', models.PositiveIntegerField(blank=True, help_text='Mean delivery_duration_seconds for completed stops that day.', null=True)),
            ],
            options={
                'ordering': ['-date', 'rider_id'],
            },
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='completion_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='completion_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivered_by_rider',
            field=models.ForeignKey(blank=True, help_text='Delivery Man attributed at completion (immutable after set).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_deliveries', to='user_management.riderprofile'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds from pick/start timestamp to delivered_at when both exist.', null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='logistics_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_deliveries', to='delivery_zones.deliverylocation'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='logistics_status',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked up'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', help_text='Rider progress; empty until first logistics event.', max_length=32),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='logistics_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_deliveries', to='delivery_zones.deliveryzone'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['delivered_by_rider', 'service_date', 'meal_period', 'status'], name='orders_orde_deliver_80f546_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['logistics_status', 'service_date'], name='orders_orde_logisti_5cfd1a_idx'),
        ),
        migrations.AddField(
            model_name='deliveryactivitylog',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='orders.orderdelivery'),
        ),
        migrations.AddField(
            model_name='deliveryactivitylog',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_activity_logs', to='user_management.riderprofile'),
        ),
        migrations.AddField(
            model_name='deliverymandailysummary',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_delivery_summaries', to='user_management.riderprofile'),
        ),
        migrations.AddIndex(
            model_name='deliveryactivitylog',
            index=models.Index(fields=['rider', 'timestamp'], name='orders_deli_rider_i_4cbe77_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryactivitylog',
            index=models.Index(fields=['delivery', 'timestamp'], name='orders_deli_deliver_a8ccd9_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverymandailysummary',
            index=models.Index(fields=['date'], name='orders_deli_date_7ff395_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverymandailysummary',
            index=models.Index(fields=['rider', 'date'], name='orders_deli_rider_i_a5d3dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverymandailysummary',
            constraint=models.UniqueConstraint(fields=('rider', 'date'), name='uniq_deliveryman_daily_summary_rider_date'),
        ),
    ]
