# Generated by Django 5.2.5 on 2026-09-29 09:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_customersubscription_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwalletsettings',
            name='minimum_recharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Minimum recharge request amount (BDT); requests below this are rejected.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
