# Generated by Django 5.2.5 on 2026-09-29 16:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderwalletsettings_minimum_recharge'),
        ('user_management', '0023_delivery_zones_initial'),
        ('wallet', '0006_delivery_fee_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwalletsettings',
            name='guest_meal_box_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='One-time guest meal box price (BDT) added to published slot meal price.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='orderwalletsettings',
            name='guest_meal_monthly_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum guest meal quantity per Asia/Dhaka calendar month.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='GuestMealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('service_date', models.DateField()),
                ('meal_period', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Guest meal unit count for this purchase.', validators=[django.core.validators.MinValueValidator(1)])),
                ('base_meal_price', models.DecimalField(decimal_places=2, help_text='Published slot final meal price snapshot at purchase.', max_digits=10)),
                ('box_price', models.DecimalField(decimal_places=2, help_text='Guest box price snapshot at purchase.', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='base_meal_price + box_price at purchase.', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='unit_price × quantity at purchase.', max_digits=12)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_meal_orders', to='user_management.customerprofile')),
                ('delivery', models.ForeignKey(blank=True, help_text='Linked subscription slot stop when available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_meal_orders', to='orders.orderdelivery')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_meal_orders', to='orders.customersubscription')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_meal_orders', to='wallet.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='orders_gues_custome_c71934_idx'), models.Index(fields=['service_date', 'meal_period', 'status'], name='orders_gues_service_722041_idx'), models.Index(fields=['subscription', 'service_date', 'meal_period'], name='orders_gues_subscri_1c6635_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('customer', 'idempotency_key'), name='guest_meal_unique_idempotency_per_customer')],
            },
        ),
    ]
