# Generated by Django 5.2.5 on 2026-09-01 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('user_management', '0016_extend_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('order', 'Order'), ('wallet', 'Wallet'), ('delivery', 'Delivery'), ('promotion', 'Promotion'), ('system', 'System')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('target_type', models.CharField(choices=[('single_user', 'Single user'), ('selected_users', 'Selected users'), ('filtered_users', 'Filtered users'), ('all_users', 'All users')], max_length=30)),
                ('target_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('total_targets', models.PositiveIntegerField(default=0)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('total_skipped', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='push_campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('firebase_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.pushcampaign')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.devicetoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pushcampaign',
            index=models.Index(fields=['status', 'created_at'], name='pushcamp_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pushcampaign',
            index=models.Index(fields=['created_by', 'created_at'], name='pushcamp_creator_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pushcampaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='pushrecip_campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pushcampaignrecipient',
            index=models.Index(fields=['user', 'sent_at'], name='pushrecip_user_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='pushcampaignrecipient',
            index=models.Index(fields=['status', 'campaign'], name='pushrecip_status_campaign_idx'),
        ),
    ]
